services:
  archisteamfarm:
    container_name: asf
    image: ghcr.io/justarchinet/archisteamfarm:6.3.8.1
    user: 1000:1000
    volumes:
      - ./config/ASF/config:/app/config
      - ./config/ASF/plugins:/app/plugins
    restart: unless-stopped
    labels:
      tsbridge.enabled: true
      tsbridge.service.port: 1242
