services:
  immich:
    image: ghcr.io/imagegenius/immich:latest
    container_name: immich
    env_file:
      - ../.env
    environment:
      - DB_HOSTNAME=postgres14
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=localhost
      - DOCKER_MODS=imagegenius/mods:universal-redis
    volumes:
      - ./config/immich:/config
      - ${DRIVE_DIRECTORY}/immich:/photos
    ports:
      - "8081:8080"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    depends_on:
      - postgres14
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/server-info"]
      interval: 1m
      timeout: 10s
      retries: 3
    labels:
      tsdproxy.enable: "true"

  postgres14:
    container_name: postgres14
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: immich
    ports:
      - "5432:5432"
    volumes:
      - ./config/postgresql:/var/lib/postgresql/data
    restart: unless-stopped

