services:
  multi-scrobbler:
    image: foxxmd/multi-scrobbler
    container_name: ms
    env_file:
      - .env
      - ../.env
    environment:
      - BASE_URL=https://ms.${MY_DOMAIN}
    volumes:
      - "./config/multi-scrobbler:/config"
    restart: unless-stopped
    labels:
      caddy: ms.${MY_DOMAIN}
      caddy.reverse_proxy: "{{upstreams 9078}}"

