services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:14.3.9
    container_name: qbittorrent
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - ./config/qbittorrent:/config
      - ${MEDIA_DIRECTORY}/torrents:/data/torrents
    restart: unless-stopped
    labels:
      tsbridge.enabled: true
      tsbridge.service.port: 8080
