include:
  - path: 'asf/docker-compose.yaml'
  # - path: 'beets/docker-compose.yaml'
  - path: 'beets-flask/docker-compose.yaml'
  - path: 'jellyfin/docker-compose.yaml'
  - path: 'navidrome/docker-compose.yaml'
  - path: 'photos/docker-compose.yaml'
  - path: 'profilarr/docker-compose.yaml'
  - path: 'prowlarr/docker-compose.yaml'
  - path: 'qbittorrent/docker-compose.yaml'
  - path: 'radarr/docker-compose.yaml'
  - path: 'seerr/docker-compose.yaml'
  - path: 'slskd/docker-compose.yaml'
  - path: 'sonarr/docker-compose.yaml'
  - path: 'tailscale/docker-compose.yaml'
