include:
  - path: 'asf/docker-compose.yaml'
  - path: 'auth/docker-compose.yaml'
  - path: 'beets/docker-compose.yaml'
  - path: 'caddy/docker-compose.yaml'
  - path: 'copyparty/docker-compose.yaml'
  - path: 'jellyfin/docker-compose.yaml'
  - path: 'koito/docker-compose.yaml'
  - path: 'lidarr/docker-compose.yaml'
  # - path: 'miniflux/docker-compose.yaml'
  - path: 'navidrome/docker-compose.yaml'
  - path: 'photos/docker-compose.yaml'
  - path: 'profilarr/docker-compose.yaml'
  - path: 'prowlarr/docker-compose.yaml'
  - path: 'qbittorrent/docker-compose.yaml'
  - path: 'radarr/docker-compose.yaml'
  - path: 'radicale/docker-compose.yaml'
  - path: 'rss/docker-compose.yaml'
  - path: 'slskd/docker-compose.yaml'
  - path: 'sonarr/docker-compose.yaml'
  # - path: 'ttrss/docker-compose.yaml'
  - path: 'yamtrack/docker-compose.yaml'


  # - path: 'bazarr/docker-compose.yaml'
  # - path: 'dockhand/docker-compose.yaml'
  # - path: 'multi-scrobbler/docker-compose.yaml'
  # - path: 'reddit/docker-compose.yaml'
  # - path: 'syncthing/docker-compose.yaml'
