services:
  caddy:
    build: .
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DUCKDNS_TOKEN=${DUCKDNS_TOKEN}
      - CADDY_INGRESS_NETWORK=bridge
    volumes:
      - ./config:/data
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      caddy_0: "*.${MY_DOMAIN}"
      caddy_0.tls.dns: "duckdns {env.DUCKDNS_TOKEN}"
      # Auth
      caddy_1: (tinyauth_forwarder)
      caddy_1.forward_auth: tinyauth:3000
      caddy_1.forward_auth.uri: /api/auth/caddy
      caddy_1.forward_auth.copy_headers: Remote-User Remote-Name Remote-Email Remote-Groups
