services:
  yamtrack:
    container_name: yamtrack
    image: ghcr.io/fuzzygrim/yamtrack
    restart: unless-stopped
    depends_on:
      - yamtrack-redis
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - SECRET=a!qnwv%1n=y9n2kl20+i4s7f%w1angoupxj6ld1cc#g)*ws7(c
      - REDIS_URL=redis://yamtrack-redis:6379
    volumes:
      - ./config/yamtrack/db:/yamtrack/db
    labels:
      tsbridge.enabled: true
      tsbridge.service.port: 8000

  yamtrack-redis:
    container_name: yamtrack-redis
    image: redis:8-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  redis_data:
