services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - ./config/prowlarr:/config
    restart: unless-stopped
    labels:
      caddy: prowlarr.${MY_DOMAIN}
      caddy.reverse_proxy: "{{upstreams 9696}}"

