services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:2.3.5
    container_name: prowlarr
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - ./config/prowlarr:/config
    restart: unless-stopped
    labels:
      tsbridge.enabled: true
      tsbridge.service.port: 9696
