services:
  navidrome:
    image: deluan/navidrome:0.63.0
    container_name: navidrome
    user: 1000:1000
    environment:
      ND_ARTISTARTPRIORITY: artist.*, album/artist.*, folder.*, external
      ND_ALBUMPLAYCOUNTMODE: "normalized"
      ND_AGENTS: apple-music,deezer
      ND_LYRICSPRIORITY: ".lrc,lrclib-lyrics,.txt,embedded"
      # - ND_LISTENBRAINZ_BASEURL=""
    restart: unless-stopped
    volumes:
      - ./config/navidrome:/data
      - ${MEDIA_DIRECTORY}/media/music:/music:ro
    labels:
      tsbridge.enabled: true
      tsbridge.service.port: 4533

