services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    user: 1000:1000
    environment:
      - ND_ARTISTARTPRIORITY=artist.*, album/artist.*, folder.*, external
    restart: unless-stopped
    volumes:
      - ./config/navidrome:/data
      - ${MEDIA_DIRECTORY}/media/music:/music:ro
    labels:
      caddy: navidrome.${MY_DOMAIN}
      caddy.reverse_proxy: "{{upstreams 4533}}"
      # caddy.import: tinyauth_forwarder *
