services:
  beets:
    image: lscr.io/linuxserver/beets:latest
    container_name: beets
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=$TZ
    volumes:
      - ./config/beets:/config
      - ${MEDIA_DIRECTORY}/media/music:/music
      - ${MEDIA_DIRECTORY}/torrents/slskd/complete:/downloads
    restart: unless-stopped
