services:
  radarr:
    image: lscr.io/linuxserver/radarr:6.3.0
    container_name: radarr
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - ./config/radarr:/config
      - ${MEDIA_DIRECTORY}:/data
    restart: unless-stopped
    labels:
      tsbridge.enabled: true
      tsbridge.service.port: 7878
