services:
  freshrss:
    image: lscr.io/linuxserver/freshrss:latest
    container_name: freshrss
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
    volumes:
      - ./config/freshrss:/config
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    labels:
      - "tsbridge.enabled=true"
      - "tsbridge.service.port=80"

