services:
  redlib:
    image: quay.io/redlib/redlib:latest
    container_name: redlib
    user: nobody
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "--tries=1", "http://localhost:8500/settings"]
      interval: 5m
      timeout: 3s
    restart: unless-stopped
    labels:
      caddy: redlib.${MY_DOMAIN}
      caddy.reverse_proxy: "{{upstreams 8080}}"
