services:
  profilarr:
    image: santiagosayshey/profilarr:latest
    container_name: profilarr
    volumes:
      - ./config:/config
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    restart: unless-stopped
    labels:
      tsbridge.enabled: true
      tsbridge.service.port: 6868
