services:
  profilarr:
    image: ghcr.io/dictionarry-hub/profilarr:2.1.0
    container_name: profilarr
    volumes:
      - ./config:/config
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - ORIGIN=https://profilarr.bengal-teeth.ts.net
    restart: unless-stopped
    labels:
      tsbridge.enabled: true
      tsbridge.service.port: 6868
