services:
  profilarr:
    image: santiagosayshey/profilarr:latest
    container_name: profilarr
    volumes:
      - ./config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    restart: unless-stopped
    labels:
      caddy: profilarr.${MY_DOMAIN}
      caddy.reverse_proxy: "{{upstreams 6868}}"
