services:
  slskd:
    image: slskd/slskd:0.25.1
    container_name: slskd
    user: 1000:1000
    ports:
      - "5031:5031/udp"
      - "50300:50300/tcp"
    volumes:
      - ./config/slskd:/app
      - ${MEDIA_DIRECTORY}/media/music:/media/music
      - ${MEDIA_DIRECTORY}/torrents/slskd:/data/torrents/slskd
    restart: unless-stopped
    labels:
      - "tsbridge.enabled=true"
      - "tsbridge.service.port=5030"

