services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:nightly
    container_name: lidarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config/lidarr:/config
      - ${MEDIA_DIRECTORY}:/data
    restart: unless-stopped
    labels:
      tsbridge.enabled: true
      tsbridge.service.port: 8686
