services:
  syncthing:
    container_name: syncthing
    image: lscr.io/linuxserver/syncthing:latest
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - ./config/syncthing:/config
      - ${DRIVE_DIRECTORY}/files:/data1
    restart: unless-stopped
    labels:
      tsbridge.enabled: true
      tsbridge.service.port: 8384
