services:
  copyparty:
    image: copyparty/ac:latest
    container_name: copyparty
    user: "1000:1000"
    volumes:
      - ./config/copyparty:/cfg:z
      - ${DRIVE_DIRECTORY}/files:/w:z
      # - ${MEDIA_DIRECTORY}:/x:z
    environment:
      LD_PRELOAD: /usr/lib/libmimalloc-secure.so.NOPE
      PYTHONUNBUFFERED: 1
    stop_grace_period: 15s  # thumbnailer is allowed to continue finishing up for 10s after the shutdown signal
    restart: unless-stopped
    labels:
      caddy: copyparty.${MY_DOMAIN}
      caddy.reverse_proxy: "{{upstreams 3923}}"
      caddy.import: tinyauth_forwarder *

