services:
  copyparty:
    image: copyparty/ac:1.20.16
    container_name: copyparty
    user: 1000:1000
    volumes:
      - ./config/copyparty:/cfg:z
      - ${DRIVE_DIRECTORY}/files:/w:z
    environment:
      LD_PRELOAD: /usr/lib/libmimalloc-secure.so.NOPE
      PYTHONUNBUFFERED: 1
    stop_grace_period: 15s  # thumbnailer is allowed to continue finishing up for 10s after the shutdown signal
    restart: unless-stopped
    labels:
      tsbridge.enabled: true
      tsbridge.service.port: 3923
