services:
  dockhand:
    image: fnsys/dockhand:latest
    container_name: dockhand
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - dockhand_data:/app/data
    labels:
      caddy: dockhand.${MY_DOMAIN}
      caddy.reverse_proxy: "{{upstreams 3000}}"

volumes:
  dockhand_data:
